unit MainForm;

{
  Products Catalog - a small CRUD demo.

  Tech: Delphi (VCL) + FireDAC + Firebird 5.0 Embedded.

  The whole UI is created in code (FormCreate -> BuildUI) so the project
  compiles and runs without any design-time component placement. On first
  launch the application creates the database file and the PRODUCTS table
  automatically (OpenMode=OpenOrCreate), then seeds a few demo rows.
}

interface

uses
  Winapi.Windows, System.SysUtils, System.Classes, System.IOUtils,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.StdCtrls, Vcl.ExtCtrls,
  Vcl.Grids, Vcl.DBGrids, Data.DB,
  FireDAC.Stan.Intf, FireDAC.Stan.Option, FireDAC.Stan.Error,
  FireDAC.UI.Intf, FireDAC.Phys.Intf, FireDAC.Stan.Def, FireDAC.Stan.Pool,
  FireDAC.Stan.Async, FireDAC.Phys, FireDAC.Phys.FB, FireDAC.Phys.FBDef,
  FireDAC.VCLUI.Wait, FireDAC.Comp.Client, FireDAC.Comp.DataSet,
  FireDAC.DApt, FireDAC.Stan.Param;

type
  TfrmMain = class(TForm)
    procedure FormCreate(Sender: TObject);
    procedure FormDestroy(Sender: TObject);
  private
    FFBLink: TFDPhysFBDriverLink;
    FConn: TFDConnection;
    FQuery: TFDQuery;
    FSource: TDataSource;
    FGrid: TDBGrid;
    FEdCode: TEdit;
    FEdName: TEdit;
    FEdPrice: TEdit;
    FEdQty: TEdit;
    FEdSearch: TEdit;
    FCurrentID: Integer;            // -1 = adding a new record
    procedure BuildUI;
    procedure SetupConnection;
    procedure EnsureSchema;
    procedure RefreshGrid(const ASearch: string = '');
    procedure ClearInputs;
    function ValidateInputs(out ACode, AName: string;
      out APrice: Double; out AQty: Integer): Boolean;
    procedure DoNew(Sender: TObject);
    procedure DoSave(Sender: TObject);
    procedure DoDelete(Sender: TObject);
    procedure DoSearch(Sender: TObject);
    procedure DoRefresh(Sender: TObject);
    procedure GridCellClick(Column: TColumn);
  end;

var
  frmMain: TfrmMain;

implementation

{$R *.dfm}

const
  DB_FILE = 'catalog.fdb';

function AppDir: string;
begin
  Result := TPath.GetDirectoryName(ParamStr(0));
end;

{ ---------------- lifecycle ---------------- }

procedure TfrmMain.FormCreate(Sender: TObject);
begin
  FCurrentID := -1;
  BuildUI;
  SetupConnection;
  EnsureSchema;
  RefreshGrid;
end;

procedure TfrmMain.FormDestroy(Sender: TObject);
begin
  if Assigned(FConn) then
    FConn.Connected := False;
end;

{ ---------------- database ---------------- }

procedure TfrmMain.SetupConnection;
var
  ClientLib: string;
begin
  FFBLink := TFDPhysFBDriverLink.Create(Self);
  // If fbclient.dll sits next to the .exe, point the driver at it explicitly.
  ClientLib := TPath.Combine(AppDir, 'fbclient.dll');
  if TFile.Exists(ClientLib) then
    FFBLink.VendorLib := ClientLib;

  FConn := TFDConnection.Create(Self);
  FConn.LoginPrompt := False;
  FConn.DriverName := 'FB';
  // No Server param -> FireDAC uses Firebird Embedded through fbclient.dll.
  FConn.Params.Values['Database']     := TPath.Combine(AppDir, DB_FILE);
  FConn.Params.Values['User_Name']    := 'SYSDBA';
  FConn.Params.Values['Password']     := 'masterkey';
  FConn.Params.Values['CharacterSet'] := 'UTF8';
  FConn.Params.Values['OpenMode']     := 'OpenOrCreate'; // create DB on first run
  FConn.Connected := True;

  FQuery := TFDQuery.Create(Self);
  FQuery.Connection := FConn;

  FSource := TDataSource.Create(Self);
  FSource.DataSet := FQuery;
  FGrid.DataSource := FSource;
end;

procedure TfrmMain.EnsureSchema;
var
  Cnt: Integer;
begin
  // Firebird stores unquoted identifiers in upper case.
  Cnt := FConn.ExecSQLScalar(
    'select count(*) from rdb$relations ' +
    'where rdb$relation_name = ''PRODUCTS'' and rdb$view_blr is null');

  if Cnt = 0 then
  begin
    FConn.ExecSQL(
      'create table PRODUCTS (' +
      '  ID    integer generated by default as identity primary key,' +
      '  CODE  varchar(30)  not null,' +
      '  NAME  varchar(100) not null,' +
      '  PRICE numeric(12,2) default 0,' +
      '  QTY   integer default 0,' +
      '  constraint UQ_PRODUCTS_CODE unique (CODE)' +
      ')');

    // Seed a few rows so the grid is not empty on first launch.
    FConn.ExecSQL('insert into PRODUCTS (CODE, NAME, PRICE, QTY) ' +
      'values (''P-001'', ''Cotton T-Shirt'', 12.50, 120)');
    FConn.ExecSQL('insert into PRODUCTS (CODE, NAME, PRICE, QTY) ' +
      'values (''P-002'', ''Denim Jeans'', 39.90, 45)');
    FConn.ExecSQL('insert into PRODUCTS (CODE, NAME, PRICE, QTY) ' +
      'values (''P-003'', ''Wool Sweater'', 54.00, 30)');
  end;
end;

{ ---------------- UI ---------------- }

procedure TfrmMain.BuildUI;
var
  pnlTop, pnlForm: TPanel;

  function MakeLabel(AParent: TWinControl; const ACaption: string;
    ALeft, ATop: Integer): TLabel;
  begin
    Result := TLabel.Create(Self);
    Result.Parent := AParent;
    Result.Caption := ACaption;
    Result.Left := ALeft;
    Result.Top := ATop;
  end;

  function MakeEdit(AParent: TWinControl; ALeft, ATop, AWidth: Integer): TEdit;
  begin
    Result := TEdit.Create(Self);
    Result.Parent := AParent;
    Result.Left := ALeft;
    Result.Top := ATop;
    Result.Width := AWidth;
  end;

  function MakeButton(AParent: TWinControl; const ACaption: string;
    ALeft, ATop, AWidth: Integer; AHandler: TNotifyEvent): TButton;
  begin
    Result := TButton.Create(Self);
    Result.Parent := AParent;
    Result.Caption := ACaption;
    Result.Left := ALeft;
    Result.Top := ATop;
    Result.Width := AWidth;
    Result.Height := 28;
    Result.OnClick := AHandler;
  end;

begin
  // --- top: search bar ---
  pnlTop := TPanel.Create(Self);
  pnlTop.Parent := Self;
  pnlTop.Align := alTop;
  pnlTop.Height := 48;
  pnlTop.BevelOuter := bvNone;

  MakeLabel(pnlTop, 'Search:', 12, 16);
  FEdSearch := MakeEdit(pnlTop, 64, 12, 280);
  MakeButton(pnlTop, 'Find', 352, 11, 70, DoSearch);
  MakeButton(pnlTop, 'Show all', 430, 11, 80, DoRefresh);

  // --- bottom: edit form ---
  pnlForm := TPanel.Create(Self);
  pnlForm.Parent := Self;
  pnlForm.Align := alBottom;
  pnlForm.Height := 150;
  pnlForm.BevelOuter := bvNone;

  MakeLabel(pnlForm, 'Code:', 12, 14);
  FEdCode := MakeEdit(pnlForm, 80, 10, 150);
  MakeLabel(pnlForm, 'Name:', 12, 44);
  FEdName := MakeEdit(pnlForm, 80, 40, 320);
  MakeLabel(pnlForm, 'Price:', 12, 74);
  FEdPrice := MakeEdit(pnlForm, 80, 70, 120);
  MakeLabel(pnlForm, 'Qty:', 12, 104);
  FEdQty := MakeEdit(pnlForm, 80, 100, 120);

  MakeButton(pnlForm, 'New',    440, 10, 90, DoNew);
  MakeButton(pnlForm, 'Save',   440, 44, 90, DoSave);
  MakeButton(pnlForm, 'Delete', 440, 78, 90, DoDelete);

  // --- center: data grid ---
  FGrid := TDBGrid.Create(Self);
  FGrid.Parent := Self;
  FGrid.Align := alClient;
  FGrid.Options := FGrid.Options - [dgEditing]; // read-only grid; edit via form
  FGrid.OnCellClick := GridCellClick;
end;

{ ---------------- data operations ---------------- }

procedure TfrmMain.RefreshGrid(const ASearch: string);
begin
  FQuery.Close;
  if ASearch = '' then
    FQuery.SQL.Text :=
      'select ID, CODE, NAME, PRICE, QTY from PRODUCTS order by ID'
  else
  begin
    FQuery.SQL.Text :=
      'select ID, CODE, NAME, PRICE, QTY from PRODUCTS ' +
      'where upper(NAME) like upper(:s) or upper(CODE) like upper(:s) ' +
      'order by ID';
    FQuery.ParamByName('s').AsString := '%' + ASearch + '%';
  end;
  FQuery.Open;
end;

procedure TfrmMain.ClearInputs;
begin
  FCurrentID := -1;
  FEdCode.Clear;
  FEdName.Clear;
  FEdPrice.Clear;
  FEdQty.Clear;
  if FEdCode.CanFocus then
    FEdCode.SetFocus;
end;

function TfrmMain.ValidateInputs(out ACode, AName: string;
  out APrice: Double; out AQty: Integer): Boolean;
var
  fs: TFormatSettings;
begin
  Result := False;
  ACode := Trim(FEdCode.Text);
  AName := Trim(FEdName.Text);

  if ACode = '' then
  begin
    ShowMessage('Code is required.');
    FEdCode.SetFocus;
    Exit;
  end;
  if AName = '' then
  begin
    ShowMessage('Name is required.');
    FEdName.SetFocus;
    Exit;
  end;

  // Accept both '.' and ',' as decimal separator from the user.
  fs := TFormatSettings.Invariant;
  APrice := StrToFloatDef(
    StringReplace(Trim(FEdPrice.Text), ',', '.', [rfReplaceAll]), -1, fs);
  if APrice < 0 then
  begin
    ShowMessage('Price must be a non-negative number.');
    FEdPrice.SetFocus;
    Exit;
  end;

  AQty := StrToIntDef(Trim(FEdQty.Text), -1);
  if AQty < 0 then
  begin
    ShowMessage('Quantity must be a non-negative integer.');
    FEdQty.SetFocus;
    Exit;
  end;

  Result := True;
end;

{ ---------------- button handlers ---------------- }

procedure TfrmMain.DoNew(Sender: TObject);
begin
  ClearInputs;
end;

procedure TfrmMain.DoSave(Sender: TObject);
var
  Code, Name: string;
  Price: Double;
  Qty: Integer;
begin
  if not ValidateInputs(Code, Name, Price, Qty) then
    Exit;
  try
    if FCurrentID < 0 then
      FConn.ExecSQL(
        'insert into PRODUCTS (CODE, NAME, PRICE, QTY) values (:c, :n, :p, :q)',
        [Code, Name, Price, Qty])
    else
      FConn.ExecSQL(
        'update PRODUCTS set CODE=:c, NAME=:n, PRICE=:p, QTY=:q where ID=:id',
        [Code, Name, Price, Qty, FCurrentID]);
  except
    on E: EFDDBEngineException do
    begin
      ShowMessage('Database error: ' + E.Message);
      Exit;
    end;
  end;
  ClearInputs;
  RefreshGrid;
end;

procedure TfrmMain.DoDelete(Sender: TObject);
begin
  if FQuery.IsEmpty then
    Exit;
  if MessageDlg('Delete the selected product?', mtConfirmation,
       [mbYes, mbNo], 0) <> mrYes then
    Exit;
  FConn.ExecSQL('delete from PRODUCTS where ID=:id',
    [FQuery.FieldByName('ID').AsInteger]);
  ClearInputs;
  RefreshGrid;
end;

procedure TfrmMain.DoSearch(Sender: TObject);
begin
  RefreshGrid(Trim(FEdSearch.Text));
end;

procedure TfrmMain.DoRefresh(Sender: TObject);
begin
  FEdSearch.Clear;
  RefreshGrid;
end;

procedure TfrmMain.GridCellClick(Column: TColumn);
begin
  if FQuery.IsEmpty then
    Exit;
  FCurrentID    := FQuery.FieldByName('ID').AsInteger;
  FEdCode.Text  := FQuery.FieldByName('CODE').AsString;
  FEdName.Text  := FQuery.FieldByName('NAME').AsString;
  FEdPrice.Text := FormatFloat('0.00', FQuery.FieldByName('PRICE').AsFloat);
  FEdQty.Text   := FQuery.FieldByName('QTY').AsString;
end;

end.
