-- Schema for the Products Catalog demo (Firebird 5.0, SQL dialect 3).
-- The application creates this automatically on first run; this file is
-- provided for reference.

CREATE TABLE PRODUCTS (
    ID    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODE  VARCHAR(30)   NOT NULL,
    NAME  VARCHAR(100)  NOT NULL,
    PRICE NUMERIC(12,2) DEFAULT 0,
    QTY   INTEGER       DEFAULT 0,
    CONSTRAINT UQ_PRODUCTS_CODE UNIQUE (CODE)
);
